// Autogenerated jute compiler
// @generated from 'zookeeper.jute'

package proto // github.com/facebookincubator/zk/codegen/proto

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type AddWatchRequest struct {
	Path string // path
	Mode int32  // mode
}

func (r *AddWatchRequest) GetPath() string {
	if r != nil {
		return r.Path
	}
	return ""
}

func (r *AddWatchRequest) GetMode() int32 {
	if r != nil {
		return r.Mode
	}
	return 0
}

func (r *AddWatchRequest) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.Path, err = dec.ReadString()
	if err != nil {
		return err
	}
	r.Mode, err = dec.ReadInt()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *AddWatchRequest) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteString(r.Path); err != nil {
		return err
	}
	if err := enc.WriteInt(r.Mode); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *AddWatchRequest) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddWatchRequest(%+v)", *r)
}
