// Autogenerated jute compiler
// @generated from 'zookeeper.jute'

package proto // github.com/facebookincubator/zk/codegen/proto

import (
	"fmt"

	"github.com/facebookincubator/zk/codegen/data"
	"github.com/go-zookeeper/jute/lib/go/jute"
)

type GetChildren2Response struct {
	Children []string   // children
	Stat     *data.Stat // stat
}

func (r *GetChildren2Response) GetChildren() []string {
	if r != nil && r.Children != nil {
		return r.Children
	}
	return nil
}

func (r *GetChildren2Response) GetStat() *data.Stat {
	if r != nil && r.Stat != nil {
		return r.Stat
	}
	return nil
}

func (r *GetChildren2Response) Read(dec jute.Decoder) (err error) {
	var size int
	if err = dec.ReadStart(); err != nil {
		return err
	}
	size, err = dec.ReadVectorStart()
	if err != nil {
		return err
	}
	if size < 0 {
		r.Children = nil
	} else {
		r.Children = make([]string, size)
		for i := 0; i < size; i++ {
			r.Children[i], err = dec.ReadString()
			if err != nil {
				return err
			}
		}
	}
	if err = dec.ReadVectorEnd(); err != nil {
		return err
	}
	if err = dec.ReadRecord(r.Stat); err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *GetChildren2Response) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteVectorStart(len(r.Children), r.Children == nil); err != nil {
		return err
	}
	for _, v := range r.Children {
		if err := enc.WriteString(v); err != nil {
			return err
		}
	}
	if err := enc.WriteVectorEnd(); err != nil {
		return err
	}
	if err := enc.WriteRecord(r.Stat); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *GetChildren2Response) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetChildren2Response(%+v)", *r)
}
