// Autogenerated jute compiler
// @generated from 'zookeeper.jute'

package proto // github.com/facebookincubator/zk/codegen/proto

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type RemoveWatchesRequest struct {
	Path string // path
	Type int32  // type
}

func (r *RemoveWatchesRequest) GetPath() string {
	if r != nil {
		return r.Path
	}
	return ""
}

func (r *RemoveWatchesRequest) GetType() int32 {
	if r != nil {
		return r.Type
	}
	return 0
}

func (r *RemoveWatchesRequest) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.Path, err = dec.ReadString()
	if err != nil {
		return err
	}
	r.Type, err = dec.ReadInt()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *RemoveWatchesRequest) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteString(r.Path); err != nil {
		return err
	}
	if err := enc.WriteInt(r.Type); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *RemoveWatchesRequest) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemoveWatchesRequest(%+v)", *r)
}
