// Autogenerated jute compiler
// @generated from 'zookeeper.jute'

package proto // github.com/facebookincubator/zk/internal/proto

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type GetMaxChildrenResponse struct {
	Max int32 // max
}

func (r *GetMaxChildrenResponse) GetMax() int32 {
	if r != nil {
		return r.Max
	}
	return 0
}

func (r *GetMaxChildrenResponse) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.Max, err = dec.ReadInt()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *GetMaxChildrenResponse) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteInt(r.Max); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *GetMaxChildrenResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMaxChildrenResponse(%+v)", *r)
}
