// Autogenerated jute compiler
// @generated from 'zookeeper.jute'

package proto // github.com/facebookincubator/zk/internal/proto

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type MultiHeader struct {
	Type int32 // type
	Done bool  // done
	Err  int32 // err
}

func (r *MultiHeader) GetType() int32 {
	if r != nil {
		return r.Type
	}
	return 0
}

func (r *MultiHeader) GetDone() bool {
	if r != nil {
		return r.Done
	}
	return false
}

func (r *MultiHeader) GetErr() int32 {
	if r != nil {
		return r.Err
	}
	return 0
}

func (r *MultiHeader) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.Type, err = dec.ReadInt()
	if err != nil {
		return err
	}
	r.Done, err = dec.ReadBoolean()
	if err != nil {
		return err
	}
	r.Err, err = dec.ReadInt()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *MultiHeader) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteInt(r.Type); err != nil {
		return err
	}
	if err := enc.WriteBoolean(r.Done); err != nil {
		return err
	}
	if err := enc.WriteInt(r.Err); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *MultiHeader) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MultiHeader(%+v)", *r)
}
