// Autogenerated jute compiler
// @generated from 'zookeeper.jute'

package proto // github.com/facebookincubator/zk/internal/proto

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type RequestHeader struct {
	Xid  int32 // xid
	Type int32 // type
}

func (r *RequestHeader) GetXid() int32 {
	if r != nil {
		return r.Xid
	}
	return 0
}

func (r *RequestHeader) GetType() int32 {
	if r != nil {
		return r.Type
	}
	return 0
}

func (r *RequestHeader) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.Xid, err = dec.ReadInt()
	if err != nil {
		return err
	}
	r.Type, err = dec.ReadInt()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *RequestHeader) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteInt(r.Xid); err != nil {
		return err
	}
	if err := enc.WriteInt(r.Type); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *RequestHeader) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequestHeader(%+v)", *r)
}
