// Autogenerated jute compiler
// @generated from '/Users/ardi/go/src/github.com/facebookincubator/zk/internal/zookeeper.jute'

package data // github.com/facebookincubator/zk/internal/data

import (
	"fmt"

	"github.com/go-zookeeper/jute/lib/go/jute"
)

type ClientInfo struct {
	AuthScheme *string // authScheme
	User       *string // user
}

func (r *ClientInfo) Read(dec jute.Decoder) (err error) {
	if err = dec.ReadStart(); err != nil {
		return err
	}
	r.AuthScheme, err = dec.ReadUstring()
	if err != nil {
		return err
	}
	r.User, err = dec.ReadUstring()
	if err != nil {
		return err
	}
	if err = dec.ReadEnd(); err != nil {
		return err
	}
	return nil
}

func (r *ClientInfo) Write(enc jute.Encoder) error {
	if err := enc.WriteStart(); err != nil {
		return err
	}
	if err := enc.WriteUstring(r.AuthScheme); err != nil {
		return err
	}
	if err := enc.WriteUstring(r.User); err != nil {
		return err
	}
	if err := enc.WriteEnd(); err != nil {
		return err
	}
	return nil
}

func (r *ClientInfo) String() string {
	if r == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClientInfo(%+v)", *r)
}
