jute:
	jutec --outDir=.\
        -go.moduleMap=org.apache.zookeeper.server:- \
        -go.moduleMap=org.apache.zookeeper.txn:- \
        -go.moduleMap=org.apache.zookeeper: \
        -go.prefix=github.com/go-zookeeper/zk/internal \
        zookeeper.jute

